repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c "cd refl1d/webview/client && npm run lint"
        language: system
  - repo: https://github.com/biomejs/pre-commit
    rev: v0.6.1
    hooks:
      - id: biome-format
        name: biome-format
        files: \.(vue|js|ts|mjs|tsx|jsx|json)$
        args: ["--config-path", "refl1d/webview/client/biome.json"]
        additional_dependencies: ["@biomejs/biome@2.4.13"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=8192]
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      # - id: end-of-file-fixer
      # - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      # - id: ruff
      #   args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

ci:
  autoupdate_schedule: monthly
  skip: [eslint]
