name: Test webview

on:
  push:
    branches: [ webview ]
  pull_request:
    branches: [ webview ]

  workflow_dispatch:

jobs:
  test_and_build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, py: "3.10", doc: 1, whl: 1 }
          - { os: windows-latest, py: "3.10", whl: 1 }
          # pure python wheels

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.config.py }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.config.py }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel setuptools
        python -m pip install numpy scipy matplotlib periodictable scikit-learn pytest pytest-cov numba
        python -m pip install git+https://github.com/bumps/bumps@webview
        python -m pip install -r https://raw.githubusercontent.com/bumps/bumps/webview/webview-requirements
        python setup.py build

    - name: Run tests
      run: |
        pytest -v
        python check_examples.py --chisq
      env:
        MPLBACKEND: agg

    # - name: Check that the docs build (linux only)
    #   if: matrix.config.doc == 1
    #   run: |
    #     python -m pip install sphinx
    #     make -j 4 -C doc SPHINXOPTS="-W --keep-going" html
